# numpy types

In [1]:
2 ** 1000

10715086071862673209484250490600018105614048117055336074437503883703510511249361224931983788156958581275946729175531468251871452856923140435984577574698574803934567774824230985421074605062371141877954182153046474983581941267398767559165543946077062914571196477686542167660429831652624386837205668069376

In [2]:
import numpy as np

In [3]:
np.int64(2) ** 1000

0

In [4]:
arrNp = np.array([1,2,3])
arrNp

array([1, 2, 3])

In [5]:
type(arrNp)

numpy.ndarray

In [6]:
arrNp[1]

2

In [7]:
type(arrNp[1])

numpy.int32

In [9]:
arrNp.dtype

dtype('int32')

In [13]:
arr64 = np.array([1,2,3], dtype=np.int64)
arr64

array([1, 2, 3], dtype=int64)

In [14]:
arr64*arr64

array([1, 4, 9], dtype=int64)

# Speed of Numpy array multiplication

In [15]:
a1 = np.random.rand(1000000)
a2 = np.random.rand(1000000)

In [16]:
%time a1*a2

Wall time: 30.9 ms


array([0.18548037, 0.06258791, 0.05231606, ..., 0.55622314, 0.51964658,
       0.66770926])

# Dot Product

In [17]:
%time np.dot(a1,a2)

Wall time: 11.2 ms


250542.6594941062

In [19]:
a1@a2 # Dot product

250542.6594941062

# Matrix

In [22]:
mat1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
mat1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# arange/ reshape

In [24]:
v = np.arange(10)
v

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
v.reshape((5,2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [26]:
mat = np.arange(16).reshape((4,4))
mat

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [27]:
mat.shape

(4, 4)

In [29]:
mat2 = mat.reshape(2,8)
mat2

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [31]:
mat[2][2] = 100
mat2

array([[  0,   1,   2,   3,   4,   5,   6,   7],
       [  8,   9, 100,  11,  12,  13,  14,  15]])

# Slicing

In [32]:
arry = np.arange(12).reshape(3,4)
arry

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [33]:
arry[:,1]

array([1, 5, 9])

In [34]:
arry[1,:]

array([4, 5, 6, 7])

In [36]:
arry[1,:].reshape((4,1))

array([[4],
       [5],
       [6],
       [7]])

In [38]:
arry[2:,1:]

array([[ 9, 10, 11]])

In [39]:
arry[1:,2:] = 99
arry

array([[ 0,  1,  2,  3],
       [ 4,  5, 99, 99],
       [ 8,  9, 99, 99]])

# Boolean Indexing / Vectorization - faster than for loop : C/Fortran speed


In [42]:
b_arry = np.arange(6)
b_arry[np.array([True, False, True, False, True, True])]

array([0, 2, 4, 5])

In [43]:
b_arry >= 3

array([False, False, False,  True,  True,  True])

In [47]:
b_arry[(b_arry >= 3) & (b_arry < 5)]

array([3, 4])

In [48]:
b_arry = np.arange(10)
b_arry[~(b_arry >= 3) & (b_arry < 5)]

array([0, 1, 2])

In [50]:
mat = np.random.rand(5,5)
mat

array([[0.81940646, 0.39450577, 0.73746491, 0.7308112 , 0.41132187],
       [0.35551668, 0.56799833, 0.22447813, 0.47609686, 0.78247478],
       [0.25564638, 0.39220605, 0.72646369, 0.99863398, 0.63735974],
       [0.37282029, 0.1316948 , 0.13596306, 0.74111714, 0.5311328 ],
       [0.39775212, 0.82120298, 0.77190936, 0.24507199, 0.50720955]])

In [52]:
np.abs(mat-mat.mean()) > 1.1*mat.std()

array([[ True, False, False, False, False],
       [False, False,  True, False, False],
       [ True, False, False,  True, False],
       [False,  True,  True, False, False],
       [False,  True, False,  True, False]])

In [53]:
mat[np.abs(mat-mat.mean()) > 1.1*mat.std()]

array([0.81940646, 0.22447813, 0.25564638, 0.99863398, 0.1316948 ,
       0.13596306, 0.82120298, 0.24507199])

# Scalars operations on vector

In [54]:
arr = np.arange(5)+10
arr

array([10, 11, 12, 13, 14])

In [55]:
arr = np.arange(5)/10
arr

array([0. , 0.1, 0.2, 0.3, 0.4])

In [57]:
arr = np.arange(5)
arr ** 3

array([ 0,  1,  8, 27, 64], dtype=int32)

In [58]:
v1 = np.arange(3)
v2 = np.arange(3).reshape((3,1))
v1+v2

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

# Misc

In [59]:
mat = v1+v2
mat.any()

True

In [60]:
mat.all()

False

In [61]:
import this

The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!


In [66]:
mat = np.arange(12).reshape(3,4)
mat.sum(axis=1) # Sum of rows

array([ 6, 22, 38])

In [67]:
mat.sum(axis=0) # Sum of columns

array([12, 15, 18, 21])

# Saving and retrieving data - Pickle format

In [69]:
arr = np.arange(12).reshape(4,3)
data = arr.dumps()
data

b'\x80\x02cnumpy.core.multiarray\n_reconstruct\nq\x00cnumpy\nndarray\nq\x01K\x00\x85q\x02c_codecs\nencode\nq\x03X\x01\x00\x00\x00bq\x04X\x06\x00\x00\x00latin1q\x05\x86q\x06Rq\x07\x87q\x08Rq\t(K\x01K\x04K\x03\x86q\ncnumpy\ndtype\nq\x0bX\x02\x00\x00\x00i4q\x0cK\x00K\x01\x87q\rRq\x0e(K\x03X\x01\x00\x00\x00<q\x0fNNNJ\xff\xff\xff\xffJ\xff\xff\xff\xffK\x00tq\x10b\x89h\x03X0\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x02\x00\x00\x00\x03\x00\x00\x00\x04\x00\x00\x00\x05\x00\x00\x00\x06\x00\x00\x00\x07\x00\x00\x00\x08\x00\x00\x00\t\x00\x00\x00\n\x00\x00\x00\x0b\x00\x00\x00q\x11h\x05\x86q\x12Rq\x13tq\x14b.'

In [71]:
arr2 = np.loads(data)
arr2

C:\Users\adsar\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: np.loads is deprecated, use pickle.loads instead
  """Entry point for launching an IPython kernel.


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

# Vectorizing your functions

In [72]:
def divisible_by3(n):
    if not n%3:
        return 1
    return 0

divisible_by3(6)

1

In [73]:
v = np.arange(5)+10
divisible_by3(v)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [74]:
@np.vectorize
def divisible_by3(n):
    if not n%3:
        return 1
    return 0
divisible_by3(v)

array([0, 0, 1, 0, 0])